import cn from "classnames";
import * as React from "react";
import { createPortal } from "react-dom";
import { State, Props } from "./types";

import "./OverflowVisibleContainer.scss";

export class OverflowVisibleContainer extends React.Component<Props> {
	public state: State = {
		positionTop: 0,
		positionLeft: 0,
		isLoaded: false
	};

	constructor(props: Props) {
		super(props);

		this.onWindowClick = this.onWindowClick.bind(this);
	}

	private portal = document.createElement("div");

	private containerRef = React.createRef<HTMLDivElement>();

	public componentDidMount() {
		const { portal } = this;

		document.body.appendChild(portal);

		this.handleShowPopup();

		// setTimeout предотвращает обработку 
		// любого click по window
		// послужившого причиной cоздания данного компонента
		setTimeout(() => window.addEventListener("click", this.onWindowClick));
	}

	public componentWillUnmount() {
		const { portal } = this;

		document.body.removeChild(portal);
		window.removeEventListener("resize", this.handleShowPopup);
		window.removeEventListener("load", this.handleShowPopup);

		window.removeEventListener("click", this.onWindowClick);
	}

	public componentDidUpdate() {
		this.handleShowPopup();
	}

	public handleShowPopup = () => {
		const { parentRef } = this.props;
		const { positionLeft, positionTop } = this.state;

		if (parentRef && parentRef.current) {
			const rect = parentRef.current.getBoundingClientRect();
			const top = window.scrollY + rect.top + rect.height;
			const left = rect.left;

			if (top !== positionTop || left !== positionLeft) {
				this.setState({
					positionTop: top,
					positionLeft: left,
					isLoaded: true
				});
			}
		}

		window.addEventListener("resize", this.handleShowPopup);
		window.addEventListener("load", this.handleShowPopup);
	};

	private onWindowClick = (event: Event) => {
		// TODO: delete when there will be no unsupported Elements
		const notNeutralZoneElements =
			Array.from(document.getElementsByClassName("kit-overflow-isnt-neutral-zone-marker"));
		const fromEventPathElements = event.composedPath();

		const isClickInsideNotNeutralZone =
			notNeutralZoneElements.length != 0
			&& fromEventPathElements.find(
				pathElement =>
					notNeutralZoneElements
						.find(notNeutralElement => notNeutralElement == pathElement) != undefined
			) != undefined;

		if (isClickInsideNotNeutralZone) return;
		// ENDTODO

		// Wasn`t generated by a user click action
		if (!event.isTrusted) return;

		const targetNode = event.target as Node;
		const { onNeutralZoneClick } = this.props;
		const container = this.containerRef.current as HTMLDivElement;

		if (
			onNeutralZoneClick != null
			&& container != null
			&& !container.contains(targetNode)
		) {
			onNeutralZoneClick();
		}
	}

	public render() {
		const { portal } = this;
		const { positionLeft, positionTop, isLoaded } = this.state;
		const { children, className } = this.props;

		return createPortal(
			<div
				ref={this.containerRef}
				className={cn("kit-overflow-visiblecontainer", className)}
				style={{ left: positionLeft, top: positionTop }}
			>
				{isLoaded && children}
			</div>,
			portal
		);
	}
}
