name: Test CI

on:
  pull_request:
    branches-ignore: master
  push:
    branches-ignore: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
